/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_Seq.h"
#include "LED_TempInput.h"
#include "LED_TempInput_aliases.h"
#include "PWM.h"
#include "Clock_2.h"
#include "HBridge_INB.h"
#include "HBridge_INB_aliases.h"
#include "HBridge_PWM.h"
#include "HBridge_PWM_aliases.h"
#include "HBridge_INA.h"
#include "HBridge_INA_aliases.h"
#include "motorControlPWM.h"
#include "UART_LED_ISR.h"
#include "UART_LED.h"
#include "UART_LED_SPI_UART.h"
#include "UART_LED_PINS.h"
#include "UART_LED_SPI_UART_PVT.h"
#include "UART_LED_PVT.h"
#include "UART_LED_BOOT.h"
#include "PWM_Output.h"
#include "PWM_Output_aliases.h"
#include "TimeoutTimer.h"
#include "CommTimeoutISR.h"
#include "timer_clock.h"
#include "Clock_1.h"
#include "SamplingTimerISR.h"
#include "SamplingTimer.h"
#include "PWM_Enable.h"
#include "SwitchNodeTempInput.h"
#include "SwitchNodeTempInput_aliases.h"
#include "HBridge_CS.h"
#include "HBridge_CS_aliases.h"
#include "LED_Output.h"
#include "LED_Output_aliases.h"
#include "LED_Timer.h"
#include "Clock_3.h"
#include "DieTemp.h"
#include "LED_ISR.h"
#include "ack_clock.h"
#include "AckTimeoutISR.h"
#include "AckTimer.h"
#include "TestPin.h"
#include "TestPin_aliases.h"
#include "EmEEPROM.h"
#include "pwmClock.h"
#include "PotFeedBack.h"
#include "PotFeedBack_aliases.h"
#include "limitSwitch.h"
#include "limitSwitch_aliases.h"
#include "hallEffectISR.h"
#include "overCurrentTimer.h"
#include "overCurrentTimerISR.h"
#include "pwmClock_1.h"
#include "ADC_SAR_Seq_IRQ.h"
#include "ADC_SAR_Seq_intClock.h"
#include "UART_LED_SCBCLK.h"
#include "UART_LED_tx.h"
#include "UART_LED_tx_aliases.h"
#include "UART_LED_rx.h"
#include "UART_LED_rx_aliases.h"
#include "CyDividerClock.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

